export default function About() {
    return (
        <>
            <h2>Privacy</h2>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa massa ultricies mi quis hendrerit dolor magna eget est. Feugiat in fermentum posuere urna nec. Tincidunt ornare massa eget egestas purus. Turpis egestas pretium aenean pharetra magna ac. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Pretium quam vulputate dignissim suspendisse in est ante in. Consectetur adipiscing elit ut aliquam. Interdum varius sit amet mattis vulputate enim nulla. Urna porttitor rhoncus dolor purus non enim praesent. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Ornare massa eget egestas purus. Quis auctor elit sed vulputate mi. A cras semper auctor neque vitae tempus quam pellentesque. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Et pharetra pharetra massa massa ultricies. Amet nisl suscipit adipiscing bibendum est ultricies. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Mattis pellentesque id nibh tortor id.
                Bibendum est ultricies integer quis auctor elit sed vulputate. Scelerisque fermentum dui faucibus in ornare quam. Interdum velit euismod in pellentesque massa placerat. Vel quam elementum pulvinar etiam non quam lacus. Nunc consequat interdum varius sit amet mattis vulputate enim. Congue quisque egestas diam in arcu. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Senectus et netus et malesuada. Pellentesque id nibh tortor id. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Risus feugiat in ante metus dictum. Duis at consectetur lorem donec massa sapien. Eu turpis egestas pretium aenean pharetra. A scelerisque purus semper eget duis. Nisi lacus sed viverra tellus in hac. Aliquam ultrices sagittis orci a. Sit amet est placerat in egestas. Vel pretium lectus quam id leo in. Urna neque viverra justo nec ultrices.
                Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Diam sit amet nisl suscipit adipiscing bibendum. Massa sed elementum tempus egestas sed. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Elementum nisi quis eleifend quam adipiscing. Nisi lacus sed viverra tellus in hac habitasse platea. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Euismod in pellentesque massa placerat duis ultricies lacus sed.
                Amet consectetur adipiscing elit duis tristique sollicitudin. Vulputate mi sit amet mauris commodo quis. Fermentum leo vel orci porta non pulvinar. Habitant morbi tristique senectus et netus et malesuada fames. Mi bibendum neque egestas congue quisque. Ipsum dolor sit amet consectetur. Tortor id aliquet lectus proin nibh nisl condimentum. Habitant morbi tristique senectus et netus. Varius vel pharetra vel turpis nunc eget lorem. Quam id leo in vitae turpis massa. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Tempor nec feugiat nisl pretium fusce. Dignissim suspendisse in est ante in.
                Donec ultrices tincidunt arcu non sodales. Consequat nisl vel pretium lectus quam id leo. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Semper viverra nam libero justo laoreet sit amet. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Nisl vel pretium lectus quam id. Morbi tristique senectus et netus et malesuada fames. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Non tellus orci ac auctor augue mauris. Nulla aliquet porttitor lacus luctus accumsan.
            </p>
        </>
    );
}